spatie/form-backend-validation

src/Form.js
When user sending form after failed try, it should clear errors before sending request.
=> Clear errors when user tries to submit form

README.md, src/Form.js
This PR adding `processing` variable while request is being executed. It's useful when you want to block fields or submit button and also change any UI like that:
Before request
When request is executing
=> Add processing property

README.md, __tests__/Errors.test.js, src/Errors.js
Adds the ability to check for errors on any given object (e.g. "person") instead of passing the whole field name (e.g. "person.0.first_name").
=> Add errors.has check and errors.clear for object names

__tests__/Errors.test.js, src/Errors.js
Now it's impossible to use this package with authorization page because it can return errors in strings instead of arrays.
In PR laravel/framework#18213 there was try to fix this behavior, but Taylor rejected it. So I hope @freekmurze  will help to make this package to work with auth form.
In fact I'm copying behaviour of https://github.com/laravel/framework/blob/5.4/src/Illuminate/Support/MessageBag.php#L151 that is used in auth stub https://github.com/laravel/framework/blob/5.4/src/Illuminate/Auth/Console/stubs/make/views/auth/login.stub#L21
=> Allow to use strings instead of Arrays

CHANGELOG.md, __tests__/Errors.test.js, src/Errors.js, src/index.js
This PR adds the ability to seed a new `Errors` object with results you fetch yourself from the server. This is useful in a Vuex context, where you might be dispatching network requests in actions and wish to mutate the error state through a Vuex mutator.
As a result, this also adds the ability for `Errors` to be used as a stand-alone module.
=> Allow errors module to be standalone

__tests__/Errors.test.js, __tests__/Form.test.js, src/Errors.js, src/Form.js
This PR allows the axios library to be pre-configured.
Example:
```
export const commonAxiosApi = axios.create({
baseURL: A_BASE_URL,
headers: {
'Authorization': 'Bearer ' + A_TOKEN_THATS_SET
}
})
// later in a Vue component
async onSubmit () {
try {
let response = await this.form.post(this.form.action, commonAxiosApi)
// go to town
} catch (err) {
// failville
}
},
```
By doing so would allow axios instances to switched in. Default parameter means it won't break exisiting implementations.
=> Adds the ability to pass an axios instance into submit

README.md
Also `form.getError()` method should be renamed to `form.getErrors()` if it is returning Array of error messages.
=> Fix doc for form.errors.first method

src/Errors.js
`documents[0].file` was not picked up when calling `errors.has('documents')`.
=> Add support for array errors

src/Form.js
Since it's a commun practice to set Axios to the window object, at least for Laravel users, I have set it to the default http option.
=> Added window.axios to the default http option

__tests__/Form.test.js, src/Form.js, src/util.js
This PR adds a `successful` like Laravel Sparks Form module has it. It is quite helpful to receive this state info from the form itself because it removes the need to add your own success property or extra logic after the request has been completed if that logic would be something as simple as showing an alert.
```html
<div class="alert" v-if="form.successful">
Your contact information has been updated!
</div>
<button class="button" @click.prevent="update" :disabled="form.processing">
Update
</button>
```
=> add successful state property

README.md, __tests__/Form.test.js, src/Form.js
I'm using the same form to create and update.
With the populate method it's easy to setup a form with initials values and populate it afterwards.
Calling form.reset() will still restore the fields to their initial values.
=> Add a method to populate the form

__tests__/Errors.test.js, src/Errors.js
This makes `clear()` match `Errors.has()` changes made in https://github.com/spatie/form-backend-validation/pull/29
```javascript
const errors = new Errors({
'documents[0].file': ['Upload limit is 5MB.'],
'documents[1].file': ['This is clearly a .exe trojan. Shame on you.'],
});
errors.has('documents[1].file'); // true
errors.clear('documents[1]');
errors.has('documents'); // true
errors.has('documents[1].file'); // false
```
I also corrected the JSDoc of `Errors.all()`
=> Errors.clear() supports array key parameter

src/Errors.js
Deletions on objects in Javascript can not be detected in Vue.js. So to enable use of the errors library reactively we need to clone and replace the errors collection.
This fixes an issue I'm currently encountering where running `form.errors.clear('fieldName');` has no effect inside my Vue.js application because the change isn't reactive.
=> Ensure clearing an error is done reactively

CHANGELOG.md, src/Form.js
Hi guys,
Because of ssr while using nuxt you get a window is not defined error if you use it out of the box in the data section of a component and make a hard refresh. 
One possibility to avoid this issue is to use a plugin, inject it as a property on the vue instance and add the plugin with ssr=false. This get's rid of the error but then you can't call a function in the data section (like .withData()) on it because it's undefined on the server.
This pr just checks if the window is defined before trying to access axios. This tiny change makes it's possible to just use it out of the box with nuxt.
=> Check for window before trying to access axios, because of nuxt ssr

src/Form.js, src/util/objects.js
1) Fix deep array cloning by replacing shallow copying with a recursive call to `cloneDeep`.
2) Change `hasFiles` to look deeper for File existence.
=> Support array of objects deep cloning

src/util/formData.js
When there is at least one File in the form, keys holding the files and being empty are omitted from the posted data. In contrast, if there is no files at all, keys with empty values are included in the posted data.
This inconsistency is due to `objectToFormData` not appending the keys holding empty values. Eg when `object[property]` evaluates to `[]`.
This bug has major effect on data been validated at the backend.
=> Fix omitted empty values on submit

__tests__/Form.test.js, src/util/formData.js
`boolean` values are converted to their string representations (`"true"` and `"false"`) when the data object is converted to `FormData`. This causes Laravel's [boolean](https://laravel.com/docs/master/validation#rule-boolean) validation rule to fail.
The proposed update would allow for these values to be converted to `1` or `0` to allow the validation to pass or fail correctly.
=> convert boolean values to 1 or 0 when using FormData

src/util/formData.js
Now null values converts into strings 'null'. This pull request fixes it
=> Convert null to empty strings when using FormData

src/Form.js
Fixes the form data not being able to find files in deeply nested objects. Instead of iterating over the properties only, it'll deeply scan objects too. Sometimes you need specific keys in forms, so this way files can be found.
=> Form doesn't scan deeply nested objects

README.md
The `form.getError` method is actually a shortcut for `form.errors.first`, not `form.errors.get`, so this comment should indicate that it will return one error message rather than an array of many.
https://github.com/spatie/form-backend-validation/blob/a5026df8c3a3bf610e52d3080945f025db8de4a4/src/Form.js#L289-L297
=> Fix documentation of `form.getError`
